// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_dY5FMSoEY6D3aUQFs02pqS6_sh8Jd1o',
    appId: '1:370121528516:web:1037243c8712f856da2591',
    messagingSenderId: '370121528516',
    projectId: 'fir-b242c',
    authDomain: 'fir-b242c.firebaseapp.com',
    storageBucket: 'fir-b242c.appspot.com',
    measurementId: 'G-FYD050C08P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMNMHqyDHdDKHdv1hF4KheaYLcEbGSCKM',
    appId: '1:370121528516:android:ef4254e998392c96da2591',
    messagingSenderId: '370121528516',
    projectId: 'fir-b242c',
    storageBucket: 'fir-b242c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIC7G23Gf25b6Z20AxayVlw5FbG5VWN68',
    appId: '1:370121528516:ios:986e4a81a4beb98eda2591',
    messagingSenderId: '370121528516',
    projectId: 'fir-b242c',
    storageBucket: 'fir-b242c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIC7G23Gf25b6Z20AxayVlw5FbG5VWN68',
    appId: '1:370121528516:ios:f4fb361e95b2f309da2591',
    messagingSenderId: '370121528516',
    projectId: 'fir-b242c',
    storageBucket: 'fir-b242c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
